Added de-DE translation
vitordelucca/Reddunt pull request #10
Opened 2017-10-07 23:45 UTC by Yikal

See #8

2017-10-08 16:29 UTC, TiagoDanin requested changes

2017-10-08 16:29 UTC, TiagoDanin commented on Baconit/Strings/de-DE/Resources.resw
> +﻿<?xml version="1.0" encoding="utf-8"?>
Remove character: `\ufeff`

2017-10-08 16:29 UTC, TiagoDanin commented on Baconit/Strings/de-DE/Resources.resw
> +    <value>Allerzeiten</value>
`allerzeiten` is correct ?

2017-10-08 16:29 UTC, TiagoDanin commented on Baconit/Strings/de-DE/Resources.resw
> +    <value>Allerzeiten</value>
^ Same

2017-10-08 16:29 UTC, TiagoDanin commented on Baconit/Strings/de-DE/Resources.resw
> +    <value>allerzeiten</value>
^ Same

2017-10-08 16:29 UTC, TiagoDanin commented on Baconit/Strings/de-DE/Resources.resw
> +    <value>Allerzeiten</value>
^ Same

2017-10-08 16:29 UTC, TiagoDanin commented on Baconit/Strings/de-DE/Resources.resw
> +    <value>Reddunt ist ein wunderschöner Reddit® Client basierend auf Baconit, welche eine Open-Source App ist. Es ist auf allen Windows 10 Geräten verfügbar.
No line-break

2017-10-08 18:53 UTC, Yikal commented
I changed Allerzeiten to Aller Zeiten. I think both would be correct, but the official site uses Aller Zeiten so I think it would be more appropriate.

2017-10-08 18:56 UTC, TiagoDanin approved these changes
LGTM 💯

2018-07-13 05:36 UTC, Spenhouet commented
What keeps this pull request from getting merged?

2018-07-15 03:17 UTC, vitorgrs commented
Sorry for the SUPER late merge. Will do it soon! Is just lack of time!

2018-07-15 03:24 UTC, merged